/*
 * This file is generated by jOOQ.
*/
package com.assignment.fileProcessor.repository.tables.records;


import com.assignment.fileProcessor.repository.tables.Disease;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiseaseRecord extends UpdatableRecordImpl<DiseaseRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -1222497003;

    /**
     * Setter for <code>medical.disease.disease_id</code>.
     */
    public void setDiseaseId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>medical.disease.disease_id</code>.
     */
    public Integer getDiseaseId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>medical.disease.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>medical.disease.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Disease.DISEASE.DISEASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Disease.DISEASE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDiseaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiseaseRecord value1(Integer value) {
        setDiseaseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiseaseRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiseaseRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DiseaseRecord
     */
    public DiseaseRecord() {
        super(Disease.DISEASE);
    }

    /**
     * Create a detached, initialised DiseaseRecord
     */
    public DiseaseRecord(Integer diseaseId, String name) {
        super(Disease.DISEASE);

        set(0, diseaseId);
        set(1, name);
    }
}
