/*
 * This file is generated by jOOQ.
*/
package com.assignment.fileProcessor.repository.tables.records;


import com.assignment.fileProcessor.repository.tables.Doctor;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DoctorRecord extends UpdatableRecordImpl<DoctorRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 298967652;

    /**
     * Setter for <code>medical.doctor.doctor_id</code>.
     */
    public void setDoctorId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>medical.doctor.doctor_id</code>.
     */
    public Integer getDoctorId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>medical.doctor.department_id</code>.
     */
    public void setDepartmentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>medical.doctor.department_id</code>.
     */
    public Integer getDepartmentId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Doctor.DOCTOR.DOCTOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Doctor.DOCTOR.DEPARTMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDoctorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorRecord value1(Integer value) {
        setDoctorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorRecord value2(Integer value) {
        setDepartmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DoctorRecord
     */
    public DoctorRecord() {
        super(Doctor.DOCTOR);
    }

    /**
     * Create a detached, initialised DoctorRecord
     */
    public DoctorRecord(Integer doctorId, Integer departmentId) {
        super(Doctor.DOCTOR);

        set(0, doctorId);
        set(1, departmentId);
    }
}
