/*
 * This file is generated by jOOQ.
*/
package com.assignment.fileProcessor.repository;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in medical
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>medical.department_id_seq</code>
     */
    public static final Sequence<Integer> DEPARTMENT_ID_SEQ = new SequenceImpl<Integer>("department_id_seq", Medical.MEDICAL, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>medical.disease_id_seq</code>
     */
    public static final Sequence<Integer> DISEASE_ID_SEQ = new SequenceImpl<Integer>("disease_id_seq", Medical.MEDICAL, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>medical.record_id_seq</code>
     */
    public static final Sequence<Integer> RECORD_ID_SEQ = new SequenceImpl<Integer>("record_id_seq", Medical.MEDICAL, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>medical.report_id_seq</code>
     */
    public static final Sequence<Integer> REPORT_ID_SEQ = new SequenceImpl<Integer>("report_id_seq", Medical.MEDICAL, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
