/*
 * This file is generated by jOOQ.
*/
package com.assignment.fileProcessor.repository;


import com.assignment.fileProcessor.repository.tables.Department;
import com.assignment.fileProcessor.repository.tables.Disease;
import com.assignment.fileProcessor.repository.tables.Doctor;
import com.assignment.fileProcessor.repository.tables.DocumentReport;
import com.assignment.fileProcessor.repository.tables.MedicalRecord;
import com.assignment.fileProcessor.repository.tables.Patient;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in medical
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>medical.department</code>.
     */
    public static final Department DEPARTMENT = com.assignment.fileProcessor.repository.tables.Department.DEPARTMENT;

    /**
     * The table <code>medical.disease</code>.
     */
    public static final Disease DISEASE = com.assignment.fileProcessor.repository.tables.Disease.DISEASE;

    /**
     * The table <code>medical.doctor</code>.
     */
    public static final Doctor DOCTOR = com.assignment.fileProcessor.repository.tables.Doctor.DOCTOR;

    /**
     * The table <code>medical.document_report</code>.
     */
    public static final DocumentReport DOCUMENT_REPORT = com.assignment.fileProcessor.repository.tables.DocumentReport.DOCUMENT_REPORT;

    /**
     * The table <code>medical.medical_record</code>.
     */
    public static final MedicalRecord MEDICAL_RECORD = com.assignment.fileProcessor.repository.tables.MedicalRecord.MEDICAL_RECORD;

    /**
     * The table <code>medical.patient</code>.
     */
    public static final Patient PATIENT = com.assignment.fileProcessor.repository.tables.Patient.PATIENT;
}
